[package]
name = "sn420b"
version = "0.2.0"
edition = "2021"
description = "Set up an SN / Xprinter 420B label printer on Wi-Fi from Linux"
license = "MIT"
repository = "https://github.com/kenners22/sn420b-linux"

[dependencies]
libc = "0.2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
